version: '3.8'

services:
  profile-service:
    build: .
    ports:
      - "5006:5006"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    networks:
      - linksphere-net

  neo4j:
    image: neo4j:5.12
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j-data:/data
    networks:
      - linksphere-net

volumes:
  neo4j-data:

networks:
  linksphere-net:
    driver: bridge
