version: '3.8'
services:
  api-gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your-secret-key
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postService:
    build: ./postService
    ports:
      - "3000:3000"
    environment:
      - REDIS_ADDR=redis:6379
      - MONGO_URI=mongodb://mongo:27017/postService
      - MONGO_DB=postService
      - POST_SERVICE_PORT=3000
    depends_on:
      - redis
      - mongo

  feedService:
    build: ./feedService
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI_Feed=mongodb://mongo:27017/feedService
      - MONGO_DB_Feed=feedService
      - postServiceUrl=http://postService:3000
      - userServiceUrl=http://userService:3002
      - FEED_SERVICE_PORT=4000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - mongo
      - postService
      - userService

  mongo:
    image: "mongo:4.4"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=postService

  userService:
    build: ./userService
    ports:
      - "3002:3002"
    environment:
      - USER_SERVICE_PORT=3002
    depends_on:
      - postgres

  postgres:
    image: "postgres:18-alpine"
    ports:
      - "5432:5432"
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=link_sphere
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  friendService:
    build: ./friendService
    ports:
      - "3003:3003"
    environment:
      - FRIEND_SERVICE_PORT=3003
      - REDIS_URL=redis://redis:6379
    depends_on:
      - neo4j-driver

  neo4j-driver:
    image: "neo4j:5.28.1"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_URI=bolt://neo4j-driver:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

volumes:
  mongo-data:
  postgres-data: