global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'feedservice'
    static_configs:
      - targets: ['host.docker.internal:4000']
    metrics_path: /metrics

  - job_name: 'userservice'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: /metrics

  - job_name: 'postservice'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: /metrics

  - job_name: 'imageservice'
    static_configs:
      - targets: ['host.docker.internal:6000']
    metrics_path: /metrics

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] 