version: '3.8'
services:
  api-gateway:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - auth-service
      - user-service
      - post-service
      - event-service
      - notification-service
