version: '3.8'

services:
  friendservice:
    build:
      context: ./friendService
    ports:
      - "7474:7474" # Expose the friendService port
    environment:
      USER_SERVICE_URI: "http://userService:3002"
      PORT_FRIEND_SERVICE: "7474"
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USERNAME: "neo4j"
      NEO4J_PASSWORD: "password"
    depends_on:
      - neo4j
      - userservice

  neo4j:
    image: neo4j:5.12
    ports:
      - "7687:7687" # Bolt protocol port
      - "7474:7474" # Neo4j web interface port
    environment:
      - NEO4J_URI=bolt://localhost:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs

  userservice:
    image: userservice:latest
    ports:
      - "3002:3002"
    environment:
      USER_SERVICE_PORT: "3002"

volumes:
  neo4j-data:
  neo4j-logs: