version: '3.8'

services:
  friendservice:
    build:
      context: .
    container_name: friendService
    ports:
      - "3003:7474" # Expose friendservice on a different port
    environment:
      - USER_SERVICE_URI=http://userService:3002
      - PORT_FRIEND_SERVICE=7474
    depends_on:
      - neo4j
      - userservice

  neo4j:
    image: neo4j:5.12
    ports:
      - "7687:7687" # Bolt protocol port
      - "7474:7474" # Neo4j web interface port
    environment:
      # - NEO4J_URI=bolt://localhost:7687
      # - NEO4J_USERNAME=neo4j
      # - NEO4J_PASSWORD=password
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs

  userservice:
    build: ../user-service
    # container_name: userService
    ports:
      - "3002:3002"
    environment:
      - USER_SERVICE_PORT=3002
    depends_on:
      - postgres
      - redis
  postgres:
    image: "postgres:15-alpine"
    # container_name: postgres
    ports:  
      - "5432:5432"
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=link_sphere
      - POSTGRES_PASSWORD=postgres
      - DB_PORT=5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  neo4j-data:
  neo4j-logs:
  postgres-data: