version: '3.8'
services:
  notification-service:
    build: .
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGO_URI=mongodb://mongo:27017/notificationsdb
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - redis
      - kafka
    networks:
      - linksphere-net

  mongo:
    image: mongo
    container_name: notification-mongo
    ports:
      - "27017:27017"
    networks:
      - linksphere-net

  redis:
    image: redis
    container_name: notification-redis
    ports:
      - "6379:6379"
    networks:
      - linksphere-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - linksphere-net

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - linksphere-net

networks:
  linksphere-net:
    driver: bridge
